version: '3.8'

volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      device: /home/rmakinen/data/mariadb-data
      o: bind

  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      type: none
      device: /home/rmakinen/data/wordpress-data
      o: bind

networks:
  mynetwork:
    name: rosanetwork

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:rmakinen
    container_name: nginx-cont
    ports:
      - 443:443
    # depends_on:
    #   - wordpress
    networks:
      - mynetwork
    restart: always
    volumes:
      - wordpress-data:/var/www/html

  # wordpress:
  #   build:
  #     context: ./requirements/wordpress/
  #     dockerfile: Dockerfile
  #   image: wordpress:rmakinen
  #   container_name: wordpress-cont
  #   env_file: .env
  #   networks:
  #     - mynetwork
  #   restart: always
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - wordpress-data:/var/www/html

  # mariadb:
  #   build:
  #     context: ./requirements/mariadb
  #     dockerfile: Dockerfile
  #   image: mariadb:rmakinen
  #   container_name: mariadb-cont
  #   env_file: .env
  #   restart: always
  #   networks:
  #     - mynetwork
  #   volumes:
  #     - mariadb-data:/var/lib/mysql
